export default [
  {
    _id: 1,
    title: "no cat1",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "active",
    lastUpdated: "last updated",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category2", "category3"],
    parts: 0,
    chapters: 330
  },
  {
    _id: 2,
    title: "title of novel2",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "onHold",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 5,
    chapters: 150
  },
  {
    _id: 3,
    title: "title of novel3",
    author: "Author Name3",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "dropped",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 1,
    chapters: 25
  },
  {
    _id: 4,
    title: "title of novel",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "active",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 0,
    chapters: 330
  },
  {
    _id: 5,
    title: "title of novel2",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "onHold",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 5,
    chapters: 150
  },
  {
    _id: 6,
    title: "title of novel3",
    author: "Author Name3",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "dropped",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 1,
    chapters: 25
  },
  {
    _id: 7,
    title: "title of novel",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "active",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 0,
    chapters: 330
  },
  {
    _id: 8,
    title: "title of novel2",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "onHold",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 5,
    chapters: 150
  },
  {
    _id: 9,
    title: "title of novel3",
    author: "Author Name3",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "dropped",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 1,
    chapters: 25
  },
  {
    _id: 10,
    title: "title of novel",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "active",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 0,
    chapters: 330
  },
  {
    _id: 11,
    title: "title of novel2",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "onHold",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 5,
    chapters: 150
  },
  {
    _id: 12,
    title: "title of novel3",
    author: "Author Name3",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "dropped",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1", "category2", "category3"],
    parts: 1,
    chapters: 25
  },
  {
    _id: 13,
    title: "title of novel",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "active",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag3"],
    category: ["category3"],
    parts: 0,
    chapters: 330
  },
  {
    _id: 14,
    title: "title of novel2",
    author: "Author Name",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "onHold",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1"],
    category: ["category2"],
    parts: 5,
    chapters: 150
  },
  {
    _id: 15,
    title: "title of novel3",
    author: "Author Name3",
    heroImage: "https://skydemonorder.nyc3.cdn.digitaloceanspaces.com/covers/eag0RfACnP1VjmY72o1X6mXjkQylcGF0AWlCTrDO.png",
    status: "dropped",
    lastUpdated: "last updated",
    description: "description",
    myComments: "comments",
    links: ["link1", "link2", "link3"],
    alternativeNames: ["alternative names1"],
    tags: ["tag1", "tag2", "tag3"],
    category: ["category1"],
    parts: 1,
    chapters: 25
  }
]